# Akash SDL (TODO 3:00): fill in image name after pushing the Docker image
---
version: "2.0"
services:
  trustmebro:
    image: ghcr.io/OWNER/trustmebro:latest
    expose:
      - port: 8000
        as: 80
        to:
          - global: true
profiles:
  compute:
    trustmebro:
      resources:
        cpu: { units: 1 }
        memory: { size: 1Gi }
        storage: { size: 2Gi }
  placement:
    akash:
      pricing:
        trustmebro: { denom: uakt, amount: 1000 }
deployment:
  trustmebro:
    akash:
      profile: trustmebro
      count: 1
